// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATWi_cYvM0LpwSMf1HXMigHBy4pLjn4ms',
    appId: '1:927777159594:web:758060a47e69c22a7493d3',
    messagingSenderId: '927777159594',
    projectId: 'moodsync-2828f',
    authDomain: 'moodsync-2828f.firebaseapp.com',
    storageBucket: 'moodsync-2828f.firebasestorage.app',
    measurementId: 'G-J7ZSEQ4YMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKgsm-YqNmjSFylfdOaQ2EXl7FnCEk0Fg',
    appId: '1:927777159594:android:58dab1654dc68faa7493d3',
    messagingSenderId: '927777159594',
    projectId: 'moodsync-2828f',
    storageBucket: 'moodsync-2828f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxNBjj8RLgIefIj7kVzmK0_pVeFJ7dfFE',
    appId: '1:927777159594:ios:228492e4cef070377493d3',
    messagingSenderId: '927777159594',
    projectId: 'moodsync-2828f',
    storageBucket: 'moodsync-2828f.firebasestorage.app',
    iosBundleId: 'com.example.android2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxNBjj8RLgIefIj7kVzmK0_pVeFJ7dfFE',
    appId: '1:927777159594:ios:228492e4cef070377493d3',
    messagingSenderId: '927777159594',
    projectId: 'moodsync-2828f',
    storageBucket: 'moodsync-2828f.firebasestorage.app',
    iosBundleId: 'com.example.android2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATWi_cYvM0LpwSMf1HXMigHBy4pLjn4ms',
    appId: '1:927777159594:web:5ba8fefce6467c977493d3',
    messagingSenderId: '927777159594',
    projectId: 'moodsync-2828f',
    authDomain: 'moodsync-2828f.firebaseapp.com',
    storageBucket: 'moodsync-2828f.firebasestorage.app',
    measurementId: 'G-EMC55TKL00',
  );

}